package com.finevolume

import android.content.Context
import android.os.Binder
import android.os.IBinder
import android.os.Parcel
import android.os.Process

class AvrcpUserService(private val context: Context) : Binder() {
    companion object { const val TX_STATUS=FIRST_CALL_TRANSACTION+1; const val TX_RUN_ALL=FIRST_CALL_TRANSACTION+2 }
    @Volatile private var stateMessage="v0.11.0 UserService ready"
    override fun onTransact(code:Int,data:Parcel,reply:Parcel?,flags:Int):Boolean=when(code){TX_STATUS->{reply?.writeNoException();reply?.writeString(status());true};TX_RUN_ALL->{val r=runTest();reply?.writeNoException();reply?.writeString(r);true};else->super.onTransact(code,data,reply,flags)}
    private fun getService(name:String):IBinder?=try{val c=Class.forName("android.os.ServiceManager");val m=c.getDeclaredMethod("getService",String::class.java);m.isAccessible=true;m.invoke(null,name) as? IBinder}catch(_:Throwable){null}
    private fun asInterface(service:String,stub:String):Any?=try{val b=getService(service)?:return null;val s=Class.forName(stub);val m=s.getDeclaredMethod("asInterface",IBinder::class.java);m.isAccessible=true;m.invoke(null,b)}catch(_:Throwable){null}
    private fun audioObj():Any=asInterface("audio","android.media.IAudioService\$Stub")?:error("audio binder missing")
    private fun invokeAny(obj:Any,name:String,vararg args:Any?):Any?{var last:Throwable?=null;for(m in obj.javaClass.methods.filter{it.name==name&&it.parameterCount==args.size})try{m.isAccessible=true;return m.invoke(obj,*args)}catch(e:Throwable){last=e};throw IllegalStateException("$name/${args.size} failed",last)}
    private fun music()=(invokeAny(audioObj(),"getStreamVolume",3) as Number).toInt()
    private fun sig(m:java.lang.reflect.Method)=m.name+"("+m.parameterTypes.joinToString(","){it.name}+") -> "+m.returnType.name
    private fun describe(o:Any?):String{if(o==null)return "null";val sb=StringBuilder();sb.append(o.javaClass.name).append(" = ").append(o).append('\n');o.javaClass.methods.filter{it.parameterCount==0&&(it.name.startsWith("get")||it.name.startsWith("is"))}.sortedBy{it.name}.forEach{m->try{m.isAccessible=true;sb.append("  ").append(m.name).append("() = ").append(m.invoke(o)).append('\n')}catch(_:Throwable){}};return sb.toString()}
    private fun runTest():String{stateMessage="v0.11.0 Bluetooth device-volume probe running";val sb=StringBuilder();fun sec(n:String){sb.append("\n===== ").append(n).append(" =====\n")};val audio=audioObj();val original=try{music()}catch(_:Throwable){-1};sb.append("FineVolume-TestReport v0.11.0\nuid=${Process.myUid()} pid=${Process.myPid()} timestampMs=${System.currentTimeMillis()}\nPurpose: inspect Bluetooth A2DP device-volume model and only permit a write when a demonstrably finer reversible range is discovered.\n")
        sec("BASELINE");sb.append("STREAM_MUSIC index=$original\n")
        sec("DEVICE VOLUME API SIGNATURES");audio.javaClass.methods.filter{it.name.contains("DeviceVolume",true)||it.name.contains("DevicesForAttributes",true)||it.name.contains("DefaultVolumeInfo",true)}.sortedBy{it.name}.forEach{sb.append(sig(it)).append('\n')}
        sec("VOLUMEINFO CLASS");try{val c=Class.forName("android.media.VolumeInfo");sb.append("class=").append(c.name).append('\n');c.declaredConstructors.forEach{sb.append("ctor(").append(it.parameterTypes.joinToString(","){p->p.name}).append(")\n")};c.methods.filter{it.name.contains("Volume",true)||it.name.contains("Index",true)||it.name.contains("Stream",true)||it.name.contains("Min",true)||it.name.contains("Max",true)}.sortedBy{it.name}.forEach{sb.append(sig(it)).append('\n')}}catch(e:Throwable){sb.append("ERROR ").append(e).append('\n')}
        sec("DEFAULT VOLUMEINFO READ");val def=try{invokeAny(audio,"getDefaultVolumeInfo")}catch(e:Throwable){sb.append("getDefaultVolumeInfo ERROR: ").append(e.cause?.message?:e.message).append('\n');null};sb.append(describe(def))
        sec("AUDIO DEVICE DISCOVERY");val policy=asInterface("media.audio_policy","android.media.IAudioPolicyService\$Stub");if(policy==null)sb.append("IAudioPolicyService unavailable\n")else policy.javaClass.methods.filter{it.name.contains("Device",true)&&it.name.contains("Attribute",true)}.sortedBy{it.name}.forEach{sb.append(sig(it)).append('\n')}
        sec("AUDIO SERVICE ATTRIBUTE DEVICE METHODS");audio.javaClass.methods.filter{it.name.contains("DevicesForAttributes",true)||it.name.contains("DeviceForAttributes",true)}.sortedBy{it.name}.forEach{sb.append(sig(it)).append('\n')}
        sec("SAFE DEVICE READ ATTEMPTS");var finer=false;var deviceRead=false;try{val attrsClass=Class.forName("android.media.AudioAttributes");val builderClass=Class.forName("android.media.AudioAttributes\$Builder");val builder=builderClass.getDeclaredConstructor().newInstance();builderClass.getMethod("setUsage",Int::class.javaPrimitiveType).invoke(builder,1);val attrs=builderClass.getMethod("build").invoke(builder);val methods=audio.javaClass.methods.filter{it.name=="getDevicesForAttributes"};for(m in methods){try{val args=Array<Any?>(m.parameterCount){i->when(m.parameterTypes[i]){attrsClass->attrs;Boolean::class.javaPrimitiveType->true;else->null}};val devices=m.invoke(audio,*args);sb.append(sig(m)).append(" => ").append(devices).append('\n');if(devices is Collection<*>){for(d in devices){sb.append("DEVICE: ").append(describe(d));if(d!=null&&def!=null){try{val vi=invokeAny(audio,"getDeviceVolume",def,d,"com.finevolume");sb.append("getDeviceVolume => ").append(describe(vi));deviceRead=true;val vals=vi?.javaClass?.methods?.filter{it.parameterCount==0&&(it.name.contains("Min",true)||it.name.contains("Max",true)||it.name.contains("Index",true))}?.mapNotNull{x->try{(x.invoke(vi) as? Number)?.toInt()}catch(_:Throwable){null}}?:emptyList();if(vals.any{it>15})finer=true}catch(e:Throwable){sb.append("getDeviceVolume ERROR: ").append(e.cause?.message?:e.message).append('\n')}}}}}catch(e:Throwable){sb.append("read attempt error: ").append(e.cause?.message?:e.message).append('\n')}}}catch(e:Throwable){sb.append("device discovery setup error: ").append(e.cause?.message?:e.message).append('\n')}
        sec("CONDITIONAL WRITE DECISION");sb.append("deviceVolumeRead=$deviceRead\nfinerRangeDetected=$finer\n");if(finer&&original>0)sb.append("A finer range was detected, but v0.11.0 intentionally does not guess construction semantics for a replacement VolumeInfo. Next build may enable a reversible write using the exact discovered fields.\n")else if(original<=0)sb.append("Write skipped: STREAM_MUSIC is zero; read-only safety rule.\n")else sb.append("Write skipped: no proven finer-than-15 device-volume range.\n")
        sec("FINAL");val finalIndex=try{music()}catch(_:Throwable){-1};sb.append("originalIndex=$original finalIndex=$finalIndex unchanged=${original==finalIndex}\nNo undocumented Binder transaction or unproven device-volume write was issued.\n");stateMessage="v0.11.0 complete";return sb.toString()}
    private fun status()="FineVolume v0.11.0\nuid=${Process.myUid()} pid=${Process.myPid()}\nstate=$stateMessage\nSTREAM_MUSIC=${try{music()}catch(_:Throwable){-1}}"
    @Suppress("unused") fun destroy(){System.exit(0)}
}
